apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zyjyhr6en-nodejs 
  janus-idp.io/tekton: zyjyhr6en-nodejs
  backstage.io/kubernetes-id: zyjyhr6en-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zyjyhr6en-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  