apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: zyjyhr6en-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zyjyhr6en-nodejs 
  name: zyjyhr6en-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: zyjyhr6en-nodejs
    weight: 100 
